export { default as Properties } from "../graph/PropertiesBar";
export { default as AddPropertyDetails } from "./AddPropertyDetails";
export { default as CardAmenities } from "./CardAmenities";
export { default as Monthly } from "./Monthly";
export { default as PaymentOverView } from "./PaymentOverview";
export { default as PaymentTable } from "./PaymentTable";
export { default as TableProperty } from "./TableProperty";
export { default as TotalVisitor } from "./TotalVisitorCard";
export { default as ViewPropertyCard } from "./ViewPropertyCard";
