import * as Yup from "yup";

const EditLocationDetails = [
  {
    key: "1",
    // placeholder: 'Enter your name',
    name: "country",
    label: "Country *",
    placeholder: "Country",
    styleContact: "rounded-xl overflow-hidden bg-white ",
    type: "text",
    validationSchema: Yup.string().required("Country is Required"),
    initialValue: "",
    multiline: false,
    required: true,
  },
  {
    key: "2",
    // placeholder: 'Enter your email',
    name: "city",
    label: "City *",
    placeholder: "City",
    styleContact: "rounded-lg",
    type: "text",
    validationSchema: Yup.string().required(" City is Required"),
    initialValue: "",
    multiline: false,
    required: true,
  },
  {
    key: "2",
    // placeholder: 'Enter your email',
    name: "apartment",
    label: "Apartment Name *",
    placeholder: "Apartment Name ",
    styleContact: "rounded-lg",
    type: "text",
    validationSchema: Yup.string().required(" Apartment is Required"),
    initialValue: "",
    multiline: false,
    required: true,
  },
  {
    key: "2",
    // placeholder: 'Enter your email',
    name: "locality",
    label: "Locality  *",
    placeholder: "Locality ",
    styleContact: "rounded-lg",
    type: "text",
    validationSchema: Yup.string().required(" Locality Name is Required"),
    initialValue: "",
    multiline: false,
    required: true,
  },
  {
    key: "3",
    // placeholder: 'Enter your phone number',
    name: "address",
    label: "Address*",
    placeholder: "Address",
    styleContact: "rounded-lg",
    type: "number",
    validationSchema: Yup.string().required("Address is Required"),
    initialValue: "",
    multiline: true,
    rows: 2,
  },
];
export default EditLocationDetails;
