import * as Yup from "yup";

const PropertiesDetailsSchema = [
  {
    key: "1ii",
    // placeholder: 'Enter your email',
    name: "propertyName",
    label: "PropertyName *",
    placeholder: "PropertyName",
    styleContact: "rounded-lg",
    type: "number",
    validationSchema: Yup.string().required("PropertyName is required"),
    initialValue: "",

    required: true,
  },
  {
    key: "1iii",
    // placeholder: 'Enter your email',
    name: "ownerName",
    label: "Owner Name *",
    placeholder: "OwnerName",
    styleContact: "rounded-lg",
    type: "text",
    validationSchema: Yup.string().required("OwnerName is required"),
    initialValue: "",

    required: true,
  },
  {
    key: "1iv",
    // placeholder: 'Enter your email',
    name: "email",
    label: "Email *",
    placeholder: "OwnerName",
    styleContact: "rounded-lg",
    type: "text",
    validationSchema: Yup.string().required("OwnerName is required"),
    initialValue: "",

    required: true,
  },
  {
    key: "1iv",
    // placeholder: 'Enter your email',
    name: "number",
    label: "Contact Number *",
    placeholder: "Contact Number",
    styleContact: "rounded-lg",
    type: "text",
    validationSchema: Yup.string().required("Contact Number is required"),
    initialValue: "",

    required: true,
  },
  {
    key: "1vii",
    // placeholder: 'Enter your email',
    name: " bedroom",
    label: " Bedroom *",
    placeholder: " Bedroom",
    styleContact: "rounded-lg",
    type: "text",
    validationSchema: Yup.string().required("Bedroom Number is required"),
    initialValue: "",

    required: true,
  },
  {
    key: "1vii",
    // placeholder: 'Enter your email',
    name: " bath",
    label: " BathRoom *",
    placeholder: " Area",
    styleContact: "rounded-lg",
    type: "text",
    validationSchema: Yup.string().required("Area Number is required"),
    initialValue: "",

    required: true,
  },
  {
    key: "1viii",
    // placeholder: 'Enter your email',
    name: "balconies",
    label: " Balconies *",
    placeholder: " Balconies",
    styleContact: "rounded-lg",
    type: "text",
    validationSchema: Yup.string().required("Balconies is required"),
    initialValue: "",

    required: true,
  },
  {
    key: "IXX",
    // placeholder: 'Enter your email',
    name: "description",
    label: " Description *",
    placeholder: " Description",
    styleContact: "rounded-lg",
    type: "text",
    validationSchema: Yup.string().required("Description is required"),
    initialValue: "",

    required: true,
  },

  {
    key: "1",
    // placeholder: 'Enter your name',
    name: "location",
    label: "Location *",
    placeholder: "Location",
    styleContact: "rounded-lg",

    type: "text",
    validationSchema: Yup.string().required("Location required"),

    initialValue: "",

    required: true,
    contactField: {
      xs: 12,
      sm: 12,
      md: 6,
      lg: 6,
    },
  },
  {
    key: "2",
    // placeholder: 'Enter your email',
    name: "price",
    label: "Price *",
    placeholder: "Price",
    styleContact: "rounded-lg",
    type: "number",
    validationSchema: Yup.string().required("Price is required"),
    initialValue: "",

    required: true,
  },

  {
    key: "11",
    name: "floors",
    type: "text",
    placeholder: "Floors",
    button: "  Same as above",
    styleContact: "rounded-lg",
    label: "Floors *",
    validationSchema: Yup.string().required("Floors is required"),
    initialValue: "",

    required: true,
  },

  {
    key: "11",
    name: "style ",
    type: "text",
    placeholder: "Style",
    button: "  Same as above",
    styleContact: "rounded-lg",
    label: "Style  *",
    validationSchema: Yup.string().required("Style  is required"),
    initialValue: "",

    // icon: <AddLocationAlt />,
    required: true,
  },
  {
    key: "11",
    name: "built",
    type: "number",
    placeholder: "Year Built",
    button: "  Same as above",
    styleContact: "rounded-lg",
    label: "Year Built*",
    validationSchema: Yup.string().required("Year Built is required"),
    initialValue: "",

    // icon: <AddLocationAlt />,
    required: true,
  },
  {
    key: "11",
    name: "community",
    type: "text",
    placeholder: "Community",
    button: "  Same as above",
    styleContact: "rounded-lg",
    label: "Community*",
    validationSchema: Yup.string().required("Community is required"),
    initialValue: "",

    // icon: <AddLocationAlt />,
    required: true,
  },
  {
    key: "11",
    name: "lots",
    type: "text",
    placeholder: "Lots Size",
    button: "  Same as above",
    styleContact: "rounded-lg",
    label: "Lots Size*",
    validationSchema: Yup.string().required("Lots Size is required"),
    initialValue: "",

    // icon: <AddLocationAlt />,
    required: true,
  },
  {
    key: "12",
    name: "roomType",
    type: "text",
    placeholder: "Room Type",
    button: "  Same as above",
    styleContact: "rounded-lg",
    label: "Room Type*",
    validationSchema: Yup.string().required("Room Type is required"),
    initialValue: "",

    // icon: <AddLocationAlt />,
    required: true,
  },
  {
    key: "13",
    name: "floor",
    type: "text",
    placeholder: "Floor",
    button: "  Same as above",
    styleContact: "rounded-lg",
    label: "Floor*",
    validationSchema: Yup.string().required("Floor is required"),
    initialValue: "",

    // icon: <AddLocationAlt />,
    required: true,
  },
  {
    key: "14",
    name: "information",
    type: "text",
    placeholder: "Add Information",
    button: "  Same as above",
    styleContact: "rounded-lg",
    label: "Add Information*",
    validationSchema: Yup.string().required("Information is required"),
    initialValue: "",

    // icon: <AddLocationAlt />,
    required: true,
  },
  {
    key: "15",
    name: "parking",
    type: "number",
    placeholder: "Parking Fee",
    button: "  Same as above",
    styleContact: "rounded-lg",
    label: "Parking Fee*",
    validationSchema: Yup.string().required("Parking Fee is required"),
    initialValue: "",

    // icon: <AddLocationAlt />,
    required: true,
  },
  {
    key: "16",
    name: "pet",
    type: "number",
    placeholder: "Pet Policy",
    button: "  Same as above",
    styleContact: "rounded-lg",
    label: "Pet Policy*",
    validationSchema: Yup.string().required("Pet Policy is required"),
    initialValue: "",

    // icon: <AddLocationAlt />,
    required: true,
  },
];
export default PropertiesDetailsSchema;
