export { default as BasicDetailsEdit } from "./BasicDetailsEdit";
export {default as PhotoEdit} from "./PhotoEdit"
export {default as HomeEdit} from "./HomeEdit"
export {default as HomePriceEdit} from "./HomePriceEdit"
export {default as AdditionalDetails} from "./AdditionalDetails"
export {default as AdditionalDetailsEdit} from "./AdditionalDetailsEdit"
export {default as PropertyVideoEdit} from "./PropertyVideoEdit"
export {default as ParkingDetailsEdit} from "./ParkingDetailsEdit"
export {default as ParkingEdit} from "./ParkingEdit"
export {default as PricingEdit} from "./PricingEdit"
export {default as AddHomePriceDetails} from "./AddHomePriceDetails"
export {default as AddSellParkingDetailsAdd} from "./AddSellParkingDetails"
export { default as AddNewAdditionalDetails }from './AddNewAdditionalDetails'
export {default as TermEdit} from "./TermEdit"
export {default as ScheduleEdit} from "./ScheduleEdit"
export {default as ScheduleDetailsEdit} from "./ScheduleDetailsEdit"
export {default as AddScheduleDetails} from "./AddScheduleDetails"
export {default as DeleteSchedule} from "./DeleteSchedule"
export {default as Slot} from "./Slot"  
export {default as Holiday} from "./Holiday"
export {default as AddHolidayModal} from "./AddHolidayModal"
export {default as HolidayEdit} from "./HolidayEdit"
export {default as SlotStatusUpdate} from "./SlotStatusUpdate"